create table doctor
(
    id             bigint generated by default as identity,
    birth_date     date         not null,
    full_name      varchar(255) not null,
    password       varchar(255) not null,
    phone_number   varchar(255) not null,
    raw_password   varchar(255),
    username       varchar(255) not null,
    specialization varchar(255) not null,
    unit           varchar(255) not null,
    role_id        bigint,
    primary key (id)
)
create table patient
(
    id                bigint generated by default as identity,
    birth_date        date         not null,
    full_name         varchar(255) not null,
    password          varchar(255) not null,
    phone_number      varchar(255) not null,
    raw_password      varchar(255),
    username          varchar(255) not null,
    address           varchar(255) not null,
    category          varchar(255) not null,
    emergency_contact varchar(255) not null,
    role_id           bigint,
    primary key (id)
)
create table patient_vaccinations
(
    patient_id      bigint not null,
    vaccinations_id bigint not null
)
create table queue
(
    id               bigint generated by default as identity,
    application_date date not null,
    vaccination_date timestamp,
    patient_id       bigint,
    primary key (id)
)
create table role
(
    id   bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
)
create table vaccination
(
    id                     bigint generated by default as identity,
    additional_information varchar(255),
    doze_number            integer      not null,
    vaccination_date       date         not null,
    vaccine_type           varchar(255) not null,
    doctor_id              bigint,
    primary key (id)
)
alter table doctor
    add constraint UK_ctspax8ladjoxfko6qkhxwmpb unique (username)
alter table patient
    add constraint UK_avbwwnxo3348e62y2reiv3fko unique (username)
alter table patient_vaccinations
    add constraint UK_1ux3201l9cf6xgmheq0e2dxc2 unique (vaccinations_id)
alter table role
    add constraint UK_8sewwnpamngi6b1dwaa88askk unique (name)
alter table doctor
    add constraint FKpj12kdg6oddivmuxe4rcrp6i4 foreign key (role_id) references role
alter table patient
    add constraint FK6c1rqajlqivbw6x4elbi8k3af foreign key (role_id) references role
alter table patient_vaccinations
    add constraint FK9h69vqwef24s9tgsy5aow6y0l foreign key (vaccinations_id) references vaccination
alter table patient_vaccinations
    add constraint FKeqmld8a2aayjeejcsare74y8b foreign key (patient_id) references patient
alter table queue
    add constraint PATIENT_ID_FK foreign key (patient_id) references patient
alter table vaccination
    add constraint DOCTOR_ID_FK foreign key (doctor_id) references doctor
